const data = {
  users: [
    {
      name: "admin",
      email: "admin.mail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Lewis",
      email: "lewis@mail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "yamaha r6",
      brand: "yamaha",
      category: "600cc",
      image: "/photos/yamaha.png",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "High quality japanese bike",
      id: 1,
    },
    {
      name: "honda repsol",
      brand: "honda",
      category: "600cc",
      image: "/photos/repsol.png",
      price: 150,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "High quality japanese bike",
      id: 2,
    },
    {
      name: "kawasaki ninja",
      brand: "kawasaki",
      category: "600cc",
      image: "/photos/kawasaki.png",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "High quality japanese bike",
      id: 3,
    },
    {
      name: "ktm duke 390",
      brand: "ktm",
      category: "400cc",
      image: "/photos/ktm.png",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "High quality autralian bike",
      id: 4,
    },
  ],
};
module.exports = data;
